import { useEffect, useMemo, useRef, useState } from "react";
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { NavigationContainer, DarkTheme } from "@react-navigation/native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { SafeAreaProvider, SafeAreaView } from "react-native-safe-area-context";
import { StatusBar } from "expo-status-bar";
import { ArrowLeft, Cloud, FileText, Folder, LogOut, Plus, Search, Settings, Star, Wifi } from "lucide-react-native";
import { useAuthStore } from "./src/store/auth";
import { useNotesStore } from "./src/store/notes";
import { NotesList } from "./src/components/NotesList";
import { colors } from "./src/theme";

const Stack = createNativeStackNavigator();
const Tab = createBottomTabNavigator();
const navigationTheme = { ...DarkTheme, colors: { ...DarkTheme.colors, primary: colors.primary, background: colors.background, card: colors.surface, border: colors.border, text: colors.text } };

function LoginScreen({ navigation }) {
  const signIn = useAuthStore((state) => state.signIn);
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit() { setBusy(true); setError(""); const result = await signIn(email.trim(), password); setBusy(false); if (result.error) return setError(result.error.message); navigation.reset({ index: 0, routes: [{ name: "Home" }] }); }
  return <SafeAreaView style={styles.auth}><Text style={styles.brand}>EchoNotes</Text><Text style={styles.authTitle}>Welcome back</Text><Text style={styles.muted}>Sign in to sync your notes across devices.</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Email" placeholderTextColor={colors.muted} style={styles.input}/><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Password" placeholderTextColor={colors.muted} style={styles.input}/>{!!error && <Text style={styles.error}>{error}</Text>}<Pressable disabled={busy} onPress={submit} style={styles.primaryButton}><Text style={styles.primaryText}>{busy ? "Signing in…" : "Sign in"}</Text></Pressable><Pressable onPress={() => navigation.navigate("Signup")}><Text style={styles.authLink}>New to EchoNotes? <Text style={{ color: colors.primary }}>Create account</Text></Text></Pressable></SafeAreaView>;
}

function SignupScreen({ navigation }) {
  const signUp = useAuthStore((state) => state.signUp);
  const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [message,setMessage]=useState("");
  async function submit(){const {error}=await signUp(email.trim(),password,name.trim());setMessage(error?error.message:"Check your email to verify your account.");}
  return <SafeAreaView style={styles.auth}><Text style={styles.authTitle}>Create your account</Text><TextInput value={name} onChangeText={setName} placeholder="Full name" placeholderTextColor={colors.muted} style={styles.input}/><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Email" placeholderTextColor={colors.muted} style={styles.input}/><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Password" placeholderTextColor={colors.muted} style={styles.input}/><Pressable onPress={submit} style={styles.primaryButton}><Text style={styles.primaryText}>Create account</Text></Pressable>{!!message&&<Text style={[styles.muted,{textAlign:"center",marginTop:14}]}>{message}</Text>}<Pressable onPress={()=>navigation.goBack()}><Text style={styles.authLink}>Already registered? <Text style={{color:colors.primary}}>Sign in</Text></Text></Pressable></SafeAreaView>;
}

function NotesScreen({ navigation }) {
  const user=useAuthStore(s=>s.session?.user); const notes=useNotesStore(s=>s.notes); const load=useNotesStore(s=>s.load); const create=useNotesStore(s=>s.create); const[query,setQuery]=useState(""); const owner=user?.id??"guest";
  useEffect(()=>{void load(owner)},[load,owner]);
  const shown=useMemo(()=>notes.filter(n=>!n.is_deleted&&!n.is_archived&&(n.title+n.content).toLowerCase().includes(query.toLowerCase())),[notes,query]);
  async function add(){const note=await create(owner);navigation.navigate("Editor",{id:note.id});}
  return <SafeAreaView style={styles.page}><View style={styles.headingBox}><Text style={styles.eyebrow}>ECHO8V NOTES</Text><Text style={styles.pageTitle}>Your notes</Text></View><View style={styles.search}><Search size={18} color={colors.muted}/><TextInput value={query} onChangeText={setQuery} placeholder="Search notes…" placeholderTextColor={colors.muted} style={{color:colors.text,flex:1}}/></View><NotesList notes={shown} onOpen={(note)=>navigation.navigate("Editor",{id:note.id})}/><Pressable onPress={add} style={styles.fab}><Plus color="white" size={26}/></Pressable></SafeAreaView>;
}

function FavoritesScreen({ navigation }) { const notes=useNotesStore(s=>s.notes).filter(n=>n.is_favorite&&!n.is_deleted); return <SafeAreaView style={styles.page}><Text style={styles.sectionTitle}>Favorites</Text><NotesList notes={notes} empty="No favorite notes yet" onOpen={(note)=>navigation.navigate("Editor",{id:note.id})}/></SafeAreaView>; }
function FoldersScreen(){return <SafeAreaView style={[styles.page,{paddingHorizontal:18}]}><Text style={styles.sectionTitle}>Folders</Text><View style={styles.empty}><Folder color={colors.muted} size={38}/><Text style={[styles.muted,{textAlign:"center",maxWidth:260}]}>Folder management comes in the next mobile milestone.</Text></View></SafeAreaView>}
function SettingsScreen({navigation}){const session=useAuthStore(s=>s.session);const signOut=useAuthStore(s=>s.signOut);return <SafeAreaView style={[styles.page,{paddingHorizontal:18}]}><Text style={styles.sectionTitle}>Settings</Text><View style={styles.card}><Text style={styles.label}>{session?"Signed in as":"Current workspace"}</Text><Text style={styles.value}>{session?.user?.email??"Offline guest"}</Text>{!session&&<Text style={styles.label}>You can write without an account. Sign in only when you want cloud sync.</Text>}</View><View style={styles.card}><View style={styles.row}><Wifi color={colors.success} size={19}/><View><Text style={styles.value}>Offline-first</Text><Text style={styles.label}>Notes save to SQLite on this phone</Text></View></View><View style={styles.row}><Cloud color={colors.primary} size={19}/><View><Text style={styles.value}>Cloud sync</Text><Text style={styles.label}>{session?"Signed in — sync arrives in the next milestone":"Sign in when you want to sync"}</Text></View></View></View>{session?<Pressable onPress={()=>void signOut()} style={styles.logout}><LogOut color={colors.danger} size={19}/><Text style={{color:colors.danger,fontWeight:"700"}}>Sign out</Text></Pressable>:<Pressable onPress={()=>navigation.navigate("Login")} style={styles.primaryButton}><Text style={styles.primaryText}>Sign in to sync</Text></Pressable>}</SafeAreaView>}

function EditorScreen({ route, navigation }) {
  const { id }=route.params; const user=useAuthStore(s=>s.session?.user); const note=useNotesStore(s=>s.notes.find(n=>n.id===id)); const update=useNotesStore(s=>s.update); const[title,setTitle]=useState(note?.title??""); const[content,setContent]=useState(note?.content??""); const timer=useRef(null); const owner=user?.id??"guest";
  useEffect(()=>()=>clearTimeout(timer.current),[]); if(!note)return null;
  const queue=(patch)=>{clearTimeout(timer.current);timer.current=setTimeout(()=>void update(id,patch,owner),350)};
  return <KeyboardAvoidingView behavior={Platform.OS==="ios"?"padding":undefined} style={styles.page}><SafeAreaView edges={["top"]} style={styles.editorBar}><Pressable onPress={()=>navigation.goBack()} style={styles.iconButton}><ArrowLeft color={colors.text}/></Pressable><View style={{flex:1}}/><Pressable onPress={()=>void update(id,{is_favorite:!note.is_favorite},owner)} style={styles.iconButton}><Star color={note.is_favorite?colors.warning:colors.muted} fill={note.is_favorite?colors.warning:"transparent"}/></Pressable></SafeAreaView><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.editor}><TextInput value={title} onChangeText={value=>{setTitle(value);queue({title:value.trim()||"Untitled Note",content})}} multiline placeholder="Untitled Note" placeholderTextColor={colors.muted} style={styles.noteTitle}/><TextInput value={content} onChangeText={value=>{setContent(value);queue({title:title.trim()||"Untitled Note",content:value})}} multiline textAlignVertical="top" placeholder="Start writing…" placeholderTextColor={colors.muted} style={styles.noteContent}/></ScrollView></KeyboardAvoidingView>;
}

function MainTabs(){return <Tab.Navigator screenOptions={{headerShown:false,tabBarActiveTintColor:colors.primary,tabBarInactiveTintColor:colors.muted,tabBarStyle:{backgroundColor:colors.surface,borderTopColor:colors.border,height:66,paddingTop:7}}}><Tab.Screen name="Notes" component={NotesScreen} options={{tabBarIcon:({color,size})=><FileText color={color} size={size}/>}}/><Tab.Screen name="Folders" component={FoldersScreen} options={{tabBarIcon:({color,size})=><Folder color={color} size={size}/>}}/><Tab.Screen name="Favorites" component={FavoritesScreen} options={{tabBarIcon:({color,size})=><Star color={color} size={size}/>}}/><Tab.Screen name="Settings" component={SettingsScreen} options={{tabBarIcon:({color,size})=><Settings color={color} size={size}/>}}/></Tab.Navigator>}

export default function App(){const ready=useAuthStore(s=>s.ready);const initialize=useAuthStore(s=>s.initialize);useEffect(()=>{let sub;initialize().then(value=>{sub=value});return()=>sub?.unsubscribe()},[initialize]);if(!ready)return <View style={styles.loading}><ActivityIndicator color={colors.primary}/></View>;return <SafeAreaProvider><StatusBar style="light"/><NavigationContainer theme={navigationTheme}><Stack.Navigator initialRouteName="Home" screenOptions={{headerShown:false}}><Stack.Screen name="Home" component={MainTabs}/><Stack.Screen name="Editor" component={EditorScreen}/><Stack.Screen name="Login" component={LoginScreen}/><Stack.Screen name="Signup" component={SignupScreen}/></Stack.Navigator></NavigationContainer></SafeAreaProvider>}

const styles=StyleSheet.create({loading:{flex:1,justifyContent:"center",backgroundColor:colors.background},page:{flex:1,backgroundColor:colors.background},auth:{flex:1,justifyContent:"center",padding:24,backgroundColor:colors.background},brand:{color:colors.primary,fontSize:18,fontWeight:"800",marginBottom:28},authTitle:{color:colors.text,fontSize:29,fontWeight:"800"},muted:{color:colors.muted,marginTop:8,lineHeight:20},input:{height:52,borderWidth:1,borderColor:colors.border,borderRadius:13,color:colors.text,paddingHorizontal:15,marginTop:12,backgroundColor:colors.surface},primaryButton:{height:52,borderRadius:13,backgroundColor:colors.primary,alignItems:"center",justifyContent:"center",marginTop:18},primaryText:{color:"white",fontWeight:"700"},error:{color:colors.danger,marginTop:12},authLink:{color:colors.muted,textAlign:"center",marginTop:22},headingBox:{paddingHorizontal:18,paddingTop:12,paddingBottom:14},eyebrow:{color:colors.primary,fontSize:11,fontWeight:"800",letterSpacing:1.4},pageTitle:{color:colors.text,fontSize:28,fontWeight:"800",marginTop:3},sectionTitle:{color:colors.text,fontSize:28,fontWeight:"800",padding:18},search:{height:46,marginHorizontal:16,flexDirection:"row",alignItems:"center",gap:10,paddingHorizontal:14,borderRadius:13,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},fab:{position:"absolute",right:22,bottom:22,width:58,height:58,borderRadius:29,alignItems:"center",justifyContent:"center",backgroundColor:colors.primary,elevation:8},empty:{flex:1,alignItems:"center",justifyContent:"center",gap:12},card:{borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,borderRadius:15,padding:16,marginBottom:12,gap:18},row:{flexDirection:"row",alignItems:"center",gap:13},label:{color:colors.muted,fontSize:12,marginTop:3},value:{color:colors.text,fontWeight:"600"},logout:{height:50,borderWidth:1,borderColor:colors.danger+"55",borderRadius:13,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:10,marginTop:8},editorBar:{height:94,paddingHorizontal:12,flexDirection:"row",alignItems:"flex-end",paddingBottom:8,borderBottomWidth:1,borderBottomColor:colors.border},iconButton:{width:44,height:44,alignItems:"center",justifyContent:"center"},editor:{padding:20,paddingBottom:260},noteTitle:{color:colors.text,fontSize:28,fontWeight:"800",padding:0},noteContent:{color:colors.text,fontSize:16,lineHeight:25,minHeight:520,padding:0,marginTop:20}});
